### ISSUE TITLE
DS_Store might not be necessary

### ISSUE THREAD

**Issue by HilbertSpitzer** [FACN4/Week1_Day3_Project#33]
**.DS_Store** gets created automatically. But I'm not sure it's necessary for your purposes.

You can delete it or create a gitignore for it

https://www.jeffgeerling.com/blogs/jeff-geerling/stop-letting-dsstore-slow-you

https://gist.github.com/octocat/9257657

**Comment by tawfiknasser** [comment]
i will check it

**Comment by matthall8** [comment]
Thanks for this. This should now be fixed. Please can you review and close this issue if you agree?

**Comment by HilbertSpitzer** [comment]
Looks fine to me :thumbsup:
