### ISSUE TITLE
Nav bar not friendly to medium and small sized mobile devices

### ISSUE THREAD

**Issue by DenisKent** [FACN4/Week1_Day3_Project#34]
The nav bar goes on to two lines for small and medium sized mobile screens:
![image](https://user-images.githubusercontent.com/28222381/42309229-a99a3eaa-8040-11e8-95de-8a1fb0998eb1.png)

I think the best fix would be to hide the span element for mobile devices since it is not neccesery. Otherwise perhaps reduce the font size of the nav bar for mobile?

https://github.com/FACN4/Week1_Day3_Project/blob/6ff6b5d1532471debcff91d96600ad75356ce7fb/index.html#L19

**Comment by matthall8** [comment]
Thanks Denis. This has been solved in our latest iteration.

**Comment by matthall8** [comment]
Hi Denis - this should be fixed. Can you review and close if you agree? Thank you.

**Comment by DenisKent** [comment]
Good job! :sparkles:
