### ISSUE TITLE
button no displayed 

### ISSUE THREAD

**Issue by ekbassa** [FACN4/Week1_Day3_Project#36]
https://github.com/FACN4/Week1_Day3_Project/blob/6ff6b5d1532471debcff91d96600ad75356ce7fb/index.html#L13

this button quite good , I believe  that it should not hide the contents of the text or any thing else 
I suggest using margins to keep the button away from any content

**Comment by Ryan2601** [comment]
thnx for this comment but we believe the space is more important on the website and if the button hides something you can always scroll a bit down :).
thnx again.

**Comment by matthall8** [comment]
Thank you for this. We have changed this in the mobile version. We decided to keep the desktop version as it was. Please can you check and close if you are happy with the solution?

**Comment by tawfiknasser** [comment]
He is happy
:banana:
