### ISSUE TITLE
Using <hr />'s

### ISSUE THREAD

**Issue by haydnba** [FACN4/Week1_Day3_Project#37]
https://github.com/FACN4/Week1_Day3_Project/blob/6ff6b5d1532471debcff91d96600ad75356ce7fb/index.html#L86

Its fine to use things like `<hr />` in general but be aware that the convention now is to avoid using any HTML elements for controlling the appearance fo the page: HTML5 specifies that elements should only define the purpose of their content and layout/appearance should be left for CSS. For example the old HTML tags `<b>` and `<i>` (for bold and italic) are deprecated in favour of `<em>` and `<strong>`, which leave the styling up to the CSS.

🕺🏻

**Comment by matthall8** [comment]
Thanks for this. This should now be fixed. Please can you review and close this issue if you agree?

**Comment by afifisuha** [comment]
we deleted all hr /  tags from html file and added id's of about and team section using border-bottom

**Comment by haydnba** [comment]
sounds good - i trust you!
