### ISSUE TITLE
Fieldsets!

### ISSUE THREAD

**Issue by haydnba** [FACN4/Week1_Day3_Project#39]
https://github.com/FACN4/Week1_Day3_Project/blob/6ff6b5d1532471debcff91d96600ad75356ce7fb/index.html#L98-L113

Well done for grouping the form inputs within a fieldset - you could probably have put the whole form within a single fieldset and then use CSS to differentiate individual regions within the form.

🏗

**Comment by tawfiknasser** [comment]
@matthall8  is working on it  :+1:

**Comment by matthall8** [comment]
Hi Haydn. This has been fixed - please can you review?

**Comment by haydnba** [comment]
yes the code looks good - it has already been merged so I cannot add review but I approve!!
