### ISSUE TITLE
Sectioning out the CSS file

### ISSUE THREAD

**Issue by haydnba** [FACN4/Week1_Day3_Project#41]
https://github.com/FACN4/Week1_Day3_Project/blob/6ff6b5d1532471debcff91d96600ad75356ce7fb/style.css#L2

This is excellent practice for teamwork! You should remember to use this later when we a re working on writing tests for JavaScript etc. It is really helpful for avoiding merge conflicts - perhaps you could explain why to the rest of the class when you present this afternoon?

🤓

**Comment by matthall8** [comment]
Thanks Haydn!

**Comment by haydnba** [comment]
Pleasure!
