### ISSUE TITLE
Email Sending

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/Week1_Day3_Project#5]
So i need a reference for how can we receive mail from the clients
@FACN4/w1team4

**Comment by matthall8** [comment]
Hi T, 

The email address we should use is: the.a.team.msrt@gmail.com
A link to the reference doc is here: https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server#how

Let me know if you need anything further.

**Comment by tawfiknasser** [comment]
Thanks mate :tangerine:
